{
 "title": "Comet Statistics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(nginx_push_stream_module_up,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "comet subscribers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_push_stream_module_subscribers{instance=~\"$instance\"}",
     "legendFormat": "subscribers"
    }
   ]
  },
  {
   "title": "published messages (messages per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_push_stream_module_published_messages{instance=~\"$instance\"}[2m]))",
     "legendFormat": "published_messages"
    }
   ]
  },
  {
   "title": "stored_messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_push_stream_module_stored_messages{instance=~\"$instance\"}",
     "legendFormat": "stored_messages"
    }
   ]
  },
  {
   "title": "channels_in_delete",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_push_stream_module_channels_in_delete{instance=~\"$instance\"}",
     "legendFormat": "channels_in_delete"
    }
   ]
  },
  {
   "title": "channels_in_trash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_push_stream_module_channels_in_trash{instance=~\"$instance\"}",
     "legendFormat": "channels_in_trash"
    }
   ]
  },
  {
   "title": "messages_in_trash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_push_stream_module_messages_in_trash{instance=~\"$instance\"}",
     "legendFormat": "messages_in_trash"
    }
   ]
  }
 ]
}