version: '3'

services:
  nginx:
    image: paskalmaksim/nginx-push-stream-module:0.5.6
    ports:
    - 18102:80
  exporter:
    build:
      context: .
    command:
    - /app/nginx-push-stream-module-exporter
    - -nginx.address=http://nginx
    ports:
    - 18101:8102